### ISSUE TITLE
retour sur meme ligne de prompt

### ISSUE THREAD

**Issue by jefvannot** [ReQuiem42/42shteam#3]
quand le ft_select fini, son retour doit etre affiche sur la meme ligne de prompt qu'a l'appel de ft_select
QUESTION : comment ne pas bouger le curseur du old_term ? et y retourner a la fin ?

**Comment by ReQuiem42** [comment]
Si la sauvegarde n est pas utilise pour autre chose tu peu faire:

tputs(tgetstr("sc", NULL), 1, myoutc):
//sauvegarde
tputs(tgetstr("rc", NULL), 1, myoutc);
// retour a la sauvegarde
